
# Site Settings

title: Hongyu He  # Your Title 
subtitle: Electrical Engineering, Xi'an Jiaotong University 
email: nostalgia1229@gmail.com  # Your Email
description: >-  
  Hongyu He is an undergraduate student majoring in Electrical Engineering.
baseurl: "/devlopr-starter" # the subpath of your site, e.g. /blog
url: "https://hongyu-he.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Hongyu75939626
github_username:  Hongyu-He

# Navigation 

urls:
    - text: About
      url: /
    - text: Blog
      url: /blog
    - text: Shop
      url : /shop
    - text: Sample Page
      url: /sample-page
    - text: Contact Me
      url : /contact

# Author Details

author_logo: profile.jpg
author: Hongyu He
author_bio: Hi, My Name is Hongyu He. I am a senior student majoring in Electrical Engineering.  
author_email: "nostalgia1229@gmail.com"
author_location: China
author_website_url: "https://hongyu-he.github.io"

# social links
twitter_username: Hongyu75939626
github_username:  Hongyu-He
facebook_username: 何洪宇
linkedin_username: None
behance_username: None
instagram_username: None
medium_username: Hongyu He
telegram_username: None
dribbble_username: None
flickr_username: None

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: false
show_author_education_details: true
show_author_project_details: true

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: XJTU.jpg
                college_name: XJTU (Xi'an Jiaotong University)
                college_url: http://men.xjtu.edu.cn/
                college_degree: Electrical Engineer
                description: Bachelor of Engineer
                visibility: true

author_project_details:
              - project_thumbnail: FL.png
                project_title: Stochastic Channel-Based Federated Learning
                project_description: A privacy preserving methods for large distributed federated learning system.
                project_url: https://arxiv.org/abs/1910.11160
                visibility: true

                
#for comments using disqus
disqus_shortname: Hongyu-He 

# wakatime username
wakatime_username: Hongyu He

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 4
per_page: 5
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: D9WA1YKTRS # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9b # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Shop 

collections:
 - products

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build